services:
  - type: web
    name: n8n-francisco
    env: docker
    plan: free
    repo: https://github.com/franfernandez93/n8n
    branch: master
    dockerfilePath: .render/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "tuusuario"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "tucontrase√±a"
      - key: WEBHOOK_URL
        value: https://n8n-francisco.onrender.com
      - key: N8N_HOST
        value: n8n-francisco.onrender.com
      - key: N8N_PORT
        value: "5678"
